server:
  port: 8000

spring:
  application:
    name: eureka-server8000

eureka:
  instance:
    hostname: eureka8000.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8003.com:8003/eureka/
